// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class RsplSecureVaultIOSError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "RsplSecureVaultIOSError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? RsplSecureVaultIOSError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsRsplSecureVaultApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsRsplSecureVaultApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsRsplSecureVaultApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashRsplSecureVaultApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashRsplSecureVaultApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashRsplSecureVaultApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct InitRequest: Hashable {
  var bundleId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitRequest? {
    let bundleId: String? = nilOrValue(pigeonVar_list[0])

    return InitRequest(
      bundleId: bundleId
    )
  }
  func toList() -> [Any?] {
    return [
      bundleId
    ]
  }
  static func == (lhs: InitRequest, rhs: InitRequest) -> Bool {
    return deepEqualsRsplSecureVaultApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRsplSecureVaultApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EncryptRequest: Hashable {
  var plainText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EncryptRequest? {
    let plainText: String? = nilOrValue(pigeonVar_list[0])

    return EncryptRequest(
      plainText: plainText
    )
  }
  func toList() -> [Any?] {
    return [
      plainText
    ]
  }
  static func == (lhs: EncryptRequest, rhs: EncryptRequest) -> Bool {
    return deepEqualsRsplSecureVaultApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRsplSecureVaultApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DecryptRequest: Hashable {
  var cipherText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DecryptRequest? {
    let cipherText: String? = nilOrValue(pigeonVar_list[0])

    return DecryptRequest(
      cipherText: cipherText
    )
  }
  func toList() -> [Any?] {
    return [
      cipherText
    ]
  }
  static func == (lhs: DecryptRequest, rhs: DecryptRequest) -> Bool {
    return deepEqualsRsplSecureVaultApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRsplSecureVaultApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EncryptResponse: Hashable {
  var cipherText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EncryptResponse? {
    let cipherText: String? = nilOrValue(pigeonVar_list[0])

    return EncryptResponse(
      cipherText: cipherText
    )
  }
  func toList() -> [Any?] {
    return [
      cipherText
    ]
  }
  static func == (lhs: EncryptResponse, rhs: EncryptResponse) -> Bool {
    return deepEqualsRsplSecureVaultApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRsplSecureVaultApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DecryptResponse: Hashable {
  var plainText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DecryptResponse? {
    let plainText: String? = nilOrValue(pigeonVar_list[0])

    return DecryptResponse(
      plainText: plainText
    )
  }
  func toList() -> [Any?] {
    return [
      plainText
    ]
  }
  static func == (lhs: DecryptResponse, rhs: DecryptResponse) -> Bool {
    return deepEqualsRsplSecureVaultApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRsplSecureVaultApi(value: toList(), hasher: &hasher)
  }
}

private class RsplSecureVaultApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return InitRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return EncryptRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return DecryptRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return EncryptResponse.fromList(self.readValue() as! [Any?])
    case 133:
      return DecryptResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class RsplSecureVaultApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InitRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? EncryptRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? DecryptRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? EncryptResponse {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? DecryptResponse {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class RsplSecureVaultApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RsplSecureVaultApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RsplSecureVaultApiPigeonCodecWriter(data: data)
  }
}

class RsplSecureVaultApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = RsplSecureVaultApiPigeonCodec(readerWriter: RsplSecureVaultApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RsplSecureVaultApi {
  func initialize(request: InitRequest) throws
  func encrypt(request: EncryptRequest) throws -> EncryptResponse
  func decrypt(request: DecryptRequest) throws -> DecryptResponse
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RsplSecureVaultApiSetup {
  static var codec: FlutterStandardMessageCodec { RsplSecureVaultApiPigeonCodec.shared }
  /// Sets up an instance of `RsplSecureVaultApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RsplSecureVaultApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rspl_secure_vault.RsplSecureVaultApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! InitRequest
        do {
          try api.initialize(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let encryptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rspl_secure_vault.RsplSecureVaultApi.encrypt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      encryptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! EncryptRequest
        do {
          let result = try api.encrypt(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      encryptChannel.setMessageHandler(nil)
    }
    let decryptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rspl_secure_vault.RsplSecureVaultApi.decrypt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decryptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DecryptRequest
        do {
          let result = try api.decrypt(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      decryptChannel.setMessageHandler(nil)
    }
  }
}
