// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.rspl.secure_vault.rspl_secure_vault

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object RsplSecureVaultApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is RsplSecureVaultAndroidError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class RsplSecureVaultAndroidError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class InitRequest (
  val bundleId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitRequest {
      val bundleId = pigeonVar_list[0] as String?
      return InitRequest(bundleId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bundleId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is InitRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return RsplSecureVaultApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EncryptRequest (
  val plainText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EncryptRequest {
      val plainText = pigeonVar_list[0] as String?
      return EncryptRequest(plainText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      plainText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is EncryptRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return RsplSecureVaultApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecryptRequest (
  val cipherText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptRequest {
      val cipherText = pigeonVar_list[0] as String?
      return DecryptRequest(cipherText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cipherText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DecryptRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return RsplSecureVaultApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EncryptResponse (
  val cipherText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EncryptResponse {
      val cipherText = pigeonVar_list[0] as String?
      return EncryptResponse(cipherText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cipherText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is EncryptResponse) {
      return false
    }
    if (this === other) {
      return true
    }
    return RsplSecureVaultApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecryptResponse (
  val plainText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptResponse {
      val plainText = pigeonVar_list[0] as String?
      return DecryptResponse(plainText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      plainText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DecryptResponse) {
      return false
    }
    if (this === other) {
      return true
    }
    return RsplSecureVaultApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class RsplSecureVaultApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EncryptRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EncryptResponse.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is EncryptRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DecryptRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is EncryptResponse -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is DecryptResponse -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RsplSecureVaultApi {
  fun initialize(request: InitRequest)
  fun encrypt(request: EncryptRequest): EncryptResponse
  fun decrypt(request: DecryptRequest): DecryptResponse

  companion object {
    /** The codec used by RsplSecureVaultApi. */
    val codec: MessageCodec<Any?> by lazy {
      RsplSecureVaultApiPigeonCodec()
    }
    /** Sets up an instance of `RsplSecureVaultApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RsplSecureVaultApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rspl_secure_vault.RsplSecureVaultApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as InitRequest
            val wrapped: List<Any?> = try {
              api.initialize(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              RsplSecureVaultApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rspl_secure_vault.RsplSecureVaultApi.encrypt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as EncryptRequest
            val wrapped: List<Any?> = try {
              listOf(api.encrypt(requestArg))
            } catch (exception: Throwable) {
              RsplSecureVaultApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rspl_secure_vault.RsplSecureVaultApi.decrypt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DecryptRequest
            val wrapped: List<Any?> = try {
              listOf(api.decrypt(requestArg))
            } catch (exception: Throwable) {
              RsplSecureVaultApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
